export const REQUEST_INIT_CHAT_LIST = 'REQUEST_INIT_CHAT_LIST';
export const RECIEVE_INIT_CHAT_LIST = 'RECIEVE_INIT_CHAT_LIST';

export const REQUEST_CURRENT_CHAT = 'REQUEST_CURRENT_CHAT';
export const RECIEVE_CURRENT_CHAT = 'RECIEVE_CURRENT_CHAT';

export const REQUEST_CURRENT_MESSAGES = 'REQUEST_CURRENT_MESSAGES';
export const RECIEVE_CURRENT_MESSAGES = 'RECIEVE_CURRENT_MESSAGES';

export const REQUEST_SEND_MESSAGE = 'REQUEST_SEND_MESSAGE';
export const RECIEVE_SEND_MESSAGE = 'RECIEVE_SEND_MESSAGE';

export const FAIURE_FETCH_INIT_DATA = 'FAIURE_FETCH_INIT_DATA';
export const FAIURE_FETCH_CURRENT_DATA = 'FAIURE_FETCH_CURRENT_DATA';

export const CHANGE_INPUTBOX_CHANGE = 'CHANGE_INPUTBOX_CHANGE';
