export const REQUEST_INIT_CHAT_LIST = 'REQUEST_INIT_CHAT_LIST';
export const REQUEST_INIT_MESSAGES = 'REQUEST_INIT_MESSAGES';
export const RECIEVE_INIT_CHAT_LIST = 'RECIEVE_INIT_CHAT_LIST';
export const RECIEVE_INIT_MESSAGES = 'RECIEVE_INIT_MESSAGES';

export const REQUEST_CURRENT_CHAT = 'REQUEST_CURRENT_CHAT';
export const REQUEST_CURRENT_MESSAGES = 'REQUEST_CURRENT_MESSAGES';
export const RECIEVE_CURRENT_CHAT = 'RECIEVE_CURRENT_CHAT';
export const RECIEVE_CURRENT_MESSAGES = 'RECIEVE_CURRENT_MESSAGES';

export const SEND_MESSAGE = 'SEND_MESSAGE';
